TREE = 3
PLANT = 2
SPROUT = 1
SEED = 0

MIN_DEPTH_FRUITS = 30000
MIN_DEPTH_FRUITS_TRIBE = 30000
MIN_DEPTH_FRUITS_MOVEMENT = 30000
MIN_DEPTH_MEMBERS = 100
MIN_DEPTH_MEMBERS_TRIBE = 100
MIN_DEPTH_MEMBERS_MOVEMENT = 1000

# EVENTLOGS
FRUIT_TRANSFER = "frugtoverførsel"




MEMBERSHIPCHANGE = "membershipchange"



STR_INFO = "Info"
STR_RESOURCE = "Ressource"
STR_RESOURCE_LIST = 'Ressourceliste'

INFORMATION_POSITIONS = { left: 1, right: 2 }

EPICENTER_SIZES = ['Group', 'Tribe', 'Movement']