  # Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fea55da128b770377b806c25eabb45cc33bb96982f1281ab20ffab24c475cdbc23b46d2164eb95d2f0375d1bde6a1011098f0d0e5a7f703604700ddedbc5d244
  admin_email: info@newcirclemovement.org
  admin_password: 12345678
  email_provider_username: app52445102@heroku.com
  email_provider_password: stev1gok1958
  stripe_publishable_key: pk_test_ltotUdhMO1IzJjzrCp626Nxi
  stripe_webhooks_secret: whsec_aSWYcJbpajOGKZnYrKTiqEaHbqLGcRDO


test:
  secret_key_base: 450cfa83f6d5821856c8853afaeaea78a72e886a382a26caf1c5809ba98d90cba5e44316e430d7ba10fdd187ad97965e3b3888b8241002b106bc610974ba2d43

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_webhooks_secret: <%= ENV["STRIPE_WEBHOOKS_SECRET"] %>
  